apiVersion: v1
data:
  SPRING_DATASOURCE_URL: {{ .Values.spring_datasource_url }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.spring_datasource_username }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.spring_datasource_password }}
  VAULT_HOST: {{ .Values.vault_host }}
  SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
  PORT: "{{ .Values.port }}"
kind: ConfigMap
metadata:
  name: backend-config
