apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels: 
{{ toYaml .Values.labels | indent 4 }}
spec:
  revisionHistoryLimit: 15
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 20%
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"  
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: backend
        imagePullPolicy: Always
        env:
          - name: VAULT_TOKEN
            valueFrom:
              secretKeyRef:
                name: vault
                key: vault_token
        envFrom:
          - configMapRef:
              name: backend-config
        ports:
          - name: backend
            containerPort: {{ .Values.port }}
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: {{ .Values.port }}
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 2
          failureThreshold: 6
      imagePullSecrets:
        - name: docker-config-secret
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: backend
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: backend
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
{{ toYaml .Values.containerPolicies | indent 6 }}
