---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    app: vault
data:
  vault_token: {{ .Values.vault_token }}
type: Opaque

# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    ewogICAgImF1dGhzIjogewogICAgICAgICJodHRwczovL2dpdGxhYi5wcmFrdGlrdW0tc2VydmljZXMucnU6NTA1MCI6ewogICAgICAgICAgICAidXNlcm5hbWUiOiJhLmdheWR1a292IiwKICAgICAgICAgICAgInBhc3N3b3JkIjoiMzFHVjVBeWd1dVBKcmt4U1ZzVVkiLAogICAgICAgICAgICAiZW1haWwiOiJhbGV4ZXkudi5nYXlkdWtvdkB5YW5kZXgucnUiLAogICAgICAgICAgICAiYXV0aCI6IllTNW5ZWGxrZFd0dmRqb3pNVWRXTlVGNVozVjFVRXB5YTNoVFZuTlZXUT09IgogICAgCX0KICAgIH0KfQo=
type: kubernetes.io/dockerconfigjson

