.prepare_env:
  environment:
    name: k8s-sausage
    url: https://gaydukov-08.k8s.praktikum-services.tech/
  before_script:
    - mkdir -p ~/.kube
    - echo -n "${CONFIG}"|base64 -d>~/.kube/config

stages:
#  - build
#  - upload
  - deploy

#sausage-store-helm-build:
#  stage: build
#  image: alpine/helm
#  script:
#    - cd sausage-store-chart/helm-package
#    - helm package sausage-store
#  artifacts:
#    untracked: true

#sausage-store-helm-upload:
#  stage: upload
#  image: alpine/curl
#  dependencies:
#    - sausage-store-helm-build
#  script:
#    - cd sausage-store-chart/helm-package
#    - find . -maxdepth 1 -iname '*.tgz' -exec curl -u '${NEXUS_USER}:${NEXUS_PASS}'  http://nexus.praktikum-services.ru/repository/08-gaydukov-helm/ --upload-file '{}' \;   

sausage-store-helm-deploy:
  stage: deploy
  image: ubuntu
  extends: .prepare_env
  script:
    - curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
    - sudo apt-get install apt-transport-https --yes
    - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
    - sudo apt-get update
    - sudo apt-get install helm
    - helm version
    - helm repo add nexus ${NEXUS_URI} --username ${NEXUS_USER} --password ''${NEXUS_PASS}''
    - helm repo update nexus
    - helm upgrade --install sausage-store --atomic --timeout 15m nexus/sausage-store

