.prepare_env:
  environment:
    name: k8s-sausage
    url: https://gaydukov-08.k8s.praktikum-services.tech/
  before_script:
    - mkdir -p ~/.kube
    - echo -n "${CONFIG}"|base64 -d>~/.kube/config

stages:
#  - build
#  - upload
  - deploy

#sausage-store-helm-build:
#  stage: build
#  image: alpine/helm
#  script:
#    - cd sausage-store-chart/helm-package
#    - helm package sausage-store
#  artifacts:
#    untracked: true

#sausage-store-helm-upload:
#  stage: upload
#  image: alpine/curl
#  dependencies:
#    - sausage-store-helm-build
#  script:
#    - cd sausage-store-chart/helm-package
#    - find . -maxdepth 1 -iname '*.tgz' -exec curl -u '${NEXUS_USER}:${NEXUS_PASS}'  http://nexus.praktikum-services.ru/repository/08-gaydukov-helm/ --upload-file '{}' \;   

sausage-store-helm-deploy:
  stage: deploy
  image: ubuntu:latest
  extends: .prepare_env
  script:
    - apt update -y
    - apt install -y curl
    - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
    - helm version
    - echo ${NEXUS_URI}
    - echo ${NEXUS_USER}
    - echo ${NEXUS_PASS}
    - helm repo add nexus ${NEXUS_URI} --username ${NEXUS_USER} --password '${NEXUS_PASS}'
    - helm repo update nexus
    - helm upgrade --install sausage-store --atomic --timeout 15m nexus/sausage-store

