stages:
  - deploy

backend-report:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - mkdir -p ~/.kube
    - echo -n "${CONFIG}"|base64 -d>~/.kube/config
    - cat ~/.kube/config
    - kubectl config get-contexts
