---
# tasks file for frontend

- name: Ensure group "{{ backend_user }}" exists
  group:
    name: "{{ backend_user }}"
    state: present
  become: yes

- name: Ensure group "{{ frontend_user}}" exists
  group:
    name: "{{ frontend_user }}"
    state: present
  become: yes


- name: Create frontend-service user
  user:
    name: "{{ frontend_user }}"
    groups: "{{ frontend_user }},{{ backend_user }}"
    create_home: no
    shell: /sbin/nologin
  become: yes

- name: Create frontend-application directory
  file:
    path: "{{ frontend_workdir }}"
    state: directory
    owner: "{{ frontend_user }}"
    group: "{{ frontend_user }}"
    mode: 0755
  become: yes

- name: Ensure logs directory exists
  file:
    path: /logs
    state: directory
    owner: "{{ backend_user }}"
    group: "{{ backend_user }}"
  become: yes

- name: Deploy nodeJS
  unarchive:
    src: ./dist/node.tgz
    dest: /usr/local
  become: yes

- name: Install nodeJS http-server
  command: npm install -g http-server
  become: yes

- name: Download frontend package from artifact storage
  nexus:
    nexus: https://nexus.praktikum-services.ru
    repository: sausage-store-gaydukov-frontend
    http_user: "{{ nexus_user }}"
    http_pass: "{{ nexus_pass }}"
  register: nexus_download

- name: Untar frontend package
  unarchive:
    remote_src: yes
    src: "{{ nexus_download.filename }}"
    dest: "{{ frontend_workdir }}"
    owner: "{{ frontend_user }}"
  become: yes
        
- name: Deploy unit-file template
  template:
    src: sausage-store-frontend.service.j2
    dest: /etc/systemd/system/sausage-store-frontend.service
  become: yes

- name: Reload systemd config
  systemd:
    daemon_reload: yes
  become: yes

- name: Launch frontend service
  service:
    name: sausage-store-frontend
    state: started
  become: yes

- name: Modify iptable rules
  ansible.builtin.iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    in_interface: eth0
    destination_port: 80
    jump: DNAT
    to_destination: 127.0.0.1:9000
    comment: Redirect web traffic to localhost port 9000
  become: yes

- name: Route 80 port to localhost
  command: sysctl -w net.ipv4.conf.eth0.route_localnet=1
  become: yes

