image:
  backend: gitlab.praktikum-services.ru:5050/a.gaydukov/sausage-store/sausage-backend
  frontend: gitlab.praktikum-services.ru:5050/a.gaydukov/sausage-store/sausage-frontend
  backend-report: gitlab.praktikum-services.ru:5050/a.gaydukov/sausage-store/sausage-backend-report
  tag: kuber
imagePullPolicy: IfNotPresent
replicas: 2
service:
  port: 8080
resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "200m"

