apiVersion: v1
data:
  default: |
    server {

      listen 8080;

      location / {
        root   /var/www/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
      }

      location /api {
          proxy_pass http://backend:8080;
      }
    }
kind: ConfigMap
metadata:
  name: frontend-config
