---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  labels:
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: sausage-store
    meta.helm.sh/release-namespace: 08-a-gaydukov
spec:
  # В кластере может быть несколько Ingress Controllers, мы используем NGINX
  ingressClassName: "nginx"
  tls:
    - hosts: 
        - {{ .Values.fqdn }}
  rules:
    # Хост определяет правило направления траффика по доменному имени
  - host: {{ .Values.fqdn }}
    http:
      # Для различных путей в URL можно указать различные бэкенд-сервисы
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            # Заранее создан сервис типа ClusterIP
            # Он выступает в качестве бэкенда нашего Ingress
            name: frontend
            port:
              # У сервиса может быть несколько портов, указываем нужный нам
              number: {{ .Values.container_port }}
