apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-report
  labels: 
{{ toYaml .Values.labels | indent 4 }}
spec:
  revisionHistoryLimit: 15
  replicas: {{ .Values.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: backend-report
  template:
    metadata:
      labels:
        app: backend-report
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: backend-report
        imagePullPolicy: IfNotPresent
        ports:
          - name: backend-report
            containerPort: {{ .Values.container_port }}
        envFrom:
          - configMapRef:
              name: backend-report-config
      imagePullSecrets:
        - name: docker-config-secret

