apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-report
  labels: 
    app: backend-report
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: backend-report
  template:
    metadata:
      labels:
        app: backend-report
    spec:
      containers:
      - image: gitlab.praktikum-services.ru:5050/a.gaydukov/sausage-store/sausage-backend-report:kuber
        name: backend-report
        imagePullPolicy: IfNotPresent
        ports:
          - name: backend-report
            containerPort: 8080
        envFrom:
          - configMapRef:
              name: backend-report-config
      imagePullSecrets:
        - name: docker-config-secret

