---
# tasks file for backend
- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: yes

- name: Upgrade all system packages
  apt: upgrade=dist force_apt_get=yes autoremove=yes
  become: yes

- name: Install Java17
  apt: name=openjdk-17-jre state=present clean=yes
  become: yes

- name: Install PIP
  apt: name=python3-pip state=present 
  become: yes

- name: Create python symlinks
  command: ln -sf /usr/bin/python3 /usr/bin/python
  become: yes

- name: Reboot the VM for changes to take effect
  ansible.builtin.reboot:
  become: yes

- name: Install lxml package
  pip:
    name: lxml
  become: yes

- name: Install urllib3 package
  pip:
    name: urllib3
  become: yes

- name: Install bs4 package
  pip:
    name: bs4
  become: yes
