backend:
  image: 
    repository: gitlab.praktikum-services.ru:5050/a.gaydukov/sausage-store/sausage-backend
    tag: kuber

frontend:
  image: 
    repository: gitlab.praktikum-services.ru:5050/a.gaydukov/sausage-store/sausage-frontend
    tag: kuber
  fqdn: https://gaydukov-08.k8s.praktikum-services.tech/

backend-report:
  image: 
    repository: gitlab.praktikum-services.ru:5050/a.gaydukov/sausage-store/sausage-backend-report
    tag: kuber
# Default values for sausage-store.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

